CREATE TABLE IF NOT EXISTS session_events (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id   TEXT NOT NULL,
  user_id      TEXT NOT NULL,
  ts           BIGINT NOT NULL,
  event_type   TEXT NOT NULL,
  payload_json JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_session ON session_events(session_id);
CREATE INDEX IF NOT EXISTS idx_events_user ON session_events(user_id);

SELECT setval(
  pg_get_serial_sequence('session_events', 'id'),
  COALESCE((SELECT MAX(id) FROM session_events), 0) + 1,
  false
);
